### ISSUE TITLE
Personal Model - State

### ISSUE THREAD

**Issue by kajdreef** [TDHTTTT/MESA#20]
MCQ should be converted in state.

**Comment by jessechong** [comment]
Right now MCQ returns an array of ratings that can be passed to the personal model. The array of ratings is essentially the state of the user.

**Comment by kajdreef** [comment]
Nice, does it also actually update the personal model?

**Comment by kajdreef** [comment]
I have made sure it updates the personal model and that it is send to the server to get the right tasks. We now need to think of if we want to store previous mental states as well and use that as well. I think this is something that shouldn't be that difficult right? @jessechong

**Comment by jessechong** [comment]
Yes, it will be easy. Before the current mental state is updated, we will append the state into some data structure and store it somewhere.
Question is, where are we storing the previous mental states and in what format/data structure?

**Comment by jessechong** [comment]
@kajdreef Did you ever implement how the previous mental states are stored? I will work on that today if you haven't.

**Comment by kajdreef** [comment]
No, I haven't worked on that. I have been working on making the weather data and activity level available to the personal model. If you can work on that, that would be great. In #26 we talked about it more.

**Comment by kajdreef** [comment]
I close this issue, because the main part has been finished, and open a new issue to focus on if we want to use previous mental states to calculate the current mental state.
