### ISSUE TITLE
Personal Model - Context

### ISSUE THREAD

**Issue by kajdreef** [TDHTTTT/MESA#21]
Keep track of:
- previous recommendations [Database of previous recommendations or maybe just store in a json file?] @TDHTTTT 
- Weather [Good, Bad] @mmarano25 
- Activity [Low/High] @kajdreef 
- And build a context model on that.

**Comment by TDHTTTT** [comment]
https://github.com/TDHTTTT/MESA/pull/26#issue-260993019

**Comment by kajdreef** [comment]
Weather (after merging #39 ) and Activity has been implemented. So we still need to get:
1. Previous recommendations and an easy way to access them input maybe weather/activity/time of day and returns the particular recommendations + reviews. 
2. Figure out a way to build a context model based on that.

@TDHTTTT What is your progress on 1.?

**Comment by TDHTTTT** [comment]
What does this line in personal_model.js do?

```javascript
        var finished = _.after(2, _this.__calculateContext.bind(_this));
```

**Comment by kajdreef** [comment]
After finished is called twice calculateContext will be called and the current ‘this’ be binded to it.

**Comment by kajdreef** [comment]
With  #47 merged this issue can be closed! :)
