### ISSUE TITLE
Weather API

### ISSUE THREAD

**Issue by mmarano25** [TDHTTTT/MESA#29]
Need a backend module to provide simple weather data.

**Comment by mmarano25** [comment]
Hey guys, for weather are we going to still assume they're UCI students and set the location to Irvine?

**Comment by mmarano25** [comment]
I think for simplicity as well we'll just report if it's raining or snowing or something

**Comment by jessechong** [comment]
> Hey guys, for weather are we going to still assume they're UCI students and set the location to Irvine?

Yep. MESA is for UCI students so it makes sense that you hardcoded the location of the weather API to Irvine.

> I think for simplicity as well we'll just report if it's raining or snowing or something. It's probably not that important to us to know if it's cloudy or if it's cold, and preference would vary too much by user anyway. I think sticking with precipitation is smart.

I didn't think of that, but it totally makes sense. Let's stick with precipitation (raining, snowing, clear).
