### ISSUE TITLE
Link scraped data to tasks

### ISSUE THREAD

**Issue by kajdreef** [TDHTTTT/MESA#35]
@mmarano25 and I were discussing this there are probably two approaches for this:

1. Create a task "Go to event" and link the event data to that.
2. Add event data to all tasks with a certain label, e.g., Go for a run has the label "workout", we could add upcoming workout event to that even though they are not exactly the same.

What do you all think @TDHTTTT and @jessechong. Any volunteers to work on this? :)

**Comment by kajdreef** [comment]
Currently they are linked in a very simple way (check for the label of the task and if it is working out add 2 events to it.)

It would be awesome if this could be a bit more sophisticated, but this requires us finally creating a list of tasks. Can someone please work on this @TDHTTTT and @jessechong? 
Also this data needs to be presented to users, so can someone build the UI for this? Probaly @jessechong would be the best to do that?

**Comment by jessechong** [comment]
Okay, I will try to take a look at this
