### ISSUE TITLE
Finish task and store "Review"

### ISSUE THREAD

**Issue by kajdreef** [TDHTTTT/MESA#38]
When a user finishes a task we need  a sort of review just to see if the person liked or disliked it. This needs to be stored on the client side.

**Comment by jessechong** [comment]
Everytime a user finishes a task, they will review it and then the task will be removed form the task list.

Does that mean everytime the user updates their current state (via the survey that pops up) the task list will be refreshed with new tasks?

When do new tasks come in?

**Comment by kajdreef** [comment]
> Everytime a user finishes a task, they will review it and then the task will be removed form the task list.

No, I would just leave the task now. 

> When do new tasks come in?

When you close and open the app again ;P

**Comment by jessechong** [comment]
Reviews are storable now. Completed?

**Comment by kajdreef** [comment]
Yes, we would only need to open an issue for using stored reviews in calculating context.
